const SET_HISTORY_SEARCH = 'SET_HISTORY_SEARCH'
const SET_DEPART_DATE = 'SET_DEPART_DATE'
const SET_DETAIL_DATE = 'SET_DETAIL_DATE'
const SET_FLIGHT_DATE = 'SET_FLIGHT_DATE'
const SET_USERINFO = 'SET_USERINFO'
const SET_SEARCH_STR = 'SET_SEARCH_STR'
const SET_FILTER = 'SET_FILTER'

export default {
  SET_HISTORY_SEARCH,
  SET_DEPART_DATE,
  SET_USERINFO,
  SET_DETAIL_DATE,
  SET_FLIGHT_DATE,
  SET_SEARCH_STR,
  SET_FILTER
}
