const SET_HISTORY_SEARCH = 'SET_HISTORY_SEARCH'
const SET_DEPART_DATE = 'SET_DEPART_DATE'
const SET_USERINFO = 'SET_USERINFO'

export default {
  SET_HISTORY_SEARCH,
  SET_DEPART_DATE,
  SET_USERINFO
}
